### ISSUE TITLE
Does this work with latest Gatsby/Linaria? 

### ISSUE THREAD

**Issue by chocobuckle** [silvenon/gatsby-plugin-linaria#12]
On gatsby@2.4.8, linaria@1.3.1, gatsby-plugin-linaria@1.1.1.

I've added gatsby-plugin-linaria to gatsby-config.js, when I run 'gatsby develop' I'm just getting...

```WebpackError: Module build failed (from ./node_modules/linaria/loader.js):```

...wondering what I'm doing wrong?

**Comment by silvenon** [comment]
I just fixed one bug and published a release. I don't know if it's the bug you're having, but you can try updating. If it doesn't work, please create a demo so I can investigate. Otherwise you can close this issue if the patch fixed your problem.

**Comment by chocobuckle** [comment]
All working perfectly now. Thanks! :)
