### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by diegohaz** [silvenon/gatsby-plugin-linaria#2]
I tried to use this on gatsby-default-starter but it's throwing `Unexpected token` error. It seems that `linaria/loader` is being processed before `babel-loader`.

Reproduction: https://codesandbox.io/s/ll9184r7mz

I copied your `gatsby-node.js` file into my project and put `linaria/loader` before `babel-loader`, but it throws another error: `Error: .inputSourceMap must be a boolean, object, or undefined`

**Comment by diegohaz** [comment]
Nevermind. I forgot to add the custom babel config. Maybe it should be more obvious that it's a setup step.

**Comment by diegohaz** [comment]
By the way, `onCreateBabelConfig` seems to be useless if we always need to add the babel config.

**Comment by silvenon** [comment]
I thought it was only needed for tooling. I'll investigate.

**Comment by silvenon** [comment]
I made the documentation more explicit and removed `onCreateBabelConfig` from the plugin, because people using it need to set up the custom Babel config anyway. Hopefully in the future that won't be necessary.

**Comment by diegohaz** [comment]
Yeah. It's still weird to me how this works. I also needed to put `@babel/preset-typescript` in `babel.config.js`. Otherwise `linaria/loader` wouldn't work with typescript files. I guess it's a problem/limitation on the loader.

**Comment by silvenon** [comment]
Yeah, because Linaria has a special evaluation feature, which currently uses your project's Babel configuration file to configure the parser. It doesn't know about any modification made by Gatsby (like gatsby-plugin-typescript).

This tooling limitation is very awkward in Gatsby/Babel for other stuff too, like Jest and ESLint.
