### ISSUE TITLE
RHL / HMR does not reload

### ISSUE THREAD

**Issue by pungggi** [silvenon/gatsby-plugin-linaria#5]
Hello, I am having trouble with the HMR. Changes to styles are not updated.
The cause is probably the same as https://github.com/gatsbyjs/gatsby/pull/11032.

Could this be the default behaviour of the plugin?

**Comment by silvenon** [comment]
Thanks for reporting! Are you proposing that we turn HMR off for all `.css` files as part of this plugin? If that will solve the problem, I'm all for it.

**Comment by pungggi** [comment]
sorry the problem for me has to do with this issue https://github.com/gatsbyjs/gatsby/issues/11934... your plugin is working fine!

**Comment by pungggi** [comment]
Hello first of all, great project!
I need to reopen after having more accurate findings:
I am not sure where to start explaining my issue maybe its here may be its react hot loader..
maybe its linaria.

I am using gatsby with [react easy state](https://github.com/solkimicreb/react-easy-state).
gatsby 2.0.69 introduced a new version of react-hot -loader 4.6

As of this version Props passed to a  styled` component are not hot updated  **if they are wrapped with view from react easy state**..

For example:

Box.js
```js
import { styled } from "linaria/react"

const Box = styled.div`
  color: ${(props) => (props.color ? props.color : "red")};

export default Box
```

then i consume

index.js

```js
import { view } from 'react-easy-state'

export default view(() => {
  const classColor = css`
    color: green;
  `
  return (
     <Box padding={[30, 2, 10, 20]}>
       <div className={classColor}>
         <h1>About</h1>
       </div>
     </Box>
  )
})
```
If I change the classColor it updates.
But changing the value of the `padding` prop does not trigger a reload. This was working with gatsby 2.0.68 that uses react hot loader 4.5.

**Comment by silvenon** [comment]
Thanks for providing more details, I'll leave this open even though I'm not sure if this is specific to my Linaria integration or something else. I have to be honest though that I don't know how to debug hot reloading, I was always using tools that already had it built-in.

**Comment by pungggi** [comment]
hi thank you me either..  i stripped out linaria completely.. problem persits so I am closing here.
