### ISSUE TITLE
Extract critical CSS

### ISSUE THREAD

**Issue by silvenon** [silvenon/gatsby-plugin-linaria#7]
Gatsby stopped code-splitting CSS (gatsbyjs/gatsby#11072) so it's probably a good idea to manually [extract critical CSS](https://github.com/callstack/linaria/blob/master/docs/CRITICAL_CSS.md).

**Comment by cometkim** [comment]
YES, pretty sure.

Without manual CSS extraction/injection, this plugin is currently doing load styles from entire projects and inject in to head in production, which means every pages wait for other page's style unnecessarily.

```js
// index.js
const IndexPage = () => (
  <Layout>
    <SEO title="Home" />
    <h1>Hi people</h1>
    <p>Welcome to your new Gatsby site.</p>
    <p>Now go build something great.</p>
    <div className={css`
      max-width: 300px;
      margin-bottom: 1.45rem;
    `}>
      <Image />
    </ImageContainer>
    <Link to="/page-2/">Go to page 2</Link>
  </Layout>
)

// In another file `page-2.js`
const SecondPage = () => (
  <Layout>
    <SEO title="Page two" />
    <h1 className={css`color: red`}>Hi from the second page</h1>
    <p className={css`margin: 20px`}>Welcome to unused page</p>
    <Link to="/">Go back to the homepage</Link>
  </Layout>
)

```

![image](https://user-images.githubusercontent.com/9696352/59375853-fad7e680-8d89-11e9-847d-d6899bfc5497.png)

For instance, this response on index page contains page-2 style in its head. This would increase First Paint Time on projects with many pages or templates.

**Comment by silvenon** [comment]
SSR is still a complicated area for me 😅 PRs welcome if you know how to do it.

**Comment by cometkim** [comment]
@silvenon Yep, PR is here -> #14
