### ISSUE TITLE
TypeScript: Using the "styled" tag in runtime is not supported

### ISSUE THREAD

**Issue by IanVS** [silvenon/gatsby-plugin-linaria#9]
I'm using the latest version of everything, and found that unless I create a `babel.config.js` file as mentioned before https://github.com/silvenon/gatsby-plugin-linaria/pull/8, then I get the error `Using the "styled" tag in runtime is not supported`.  And when I do add it, then nothing is actually styled because it seems that a css file is not being created.  Still looking into that one…

**Comment by IanVS** [comment]
OK, I finally got things working, but I had to do two things:

1) Make sure that I put `gatsby-plugin-linaria` _after_ `gatsby-plugin-typescript` in my `gatsby-config.js`
2) Create a `babel.config.js` file as shown in the readme for version `1.0.2` of this plugin, _and_ add `'@babel/preset-typescript'` as explained in https://github.com/silvenon/gatsby-plugin-linaria/issues/2#issuecomment-450754264.

It would be great if there was either a way to simplify this down for typescript users, or at least make it more clear in the docs if these steps are needed.  I'd be happy to submit a docs PR if that's helpful.

**Comment by silvenon** [comment]
Thanks for inspecting the problem, it's really useful! I'll see if I can find a better way than forcing people to add `babel.config.js`. And if order of the plugins indeed is necessary (this requirement will probably be necessary) I'll try to raise a warning if it's not correct.

I must admit that this plugin composition is pretty hard, that's the only part of Gatsby that I'm not in love with. Developing this plugin will be a good opportunity to identify problems in the API itself and maybe push for improving it upstream.

**Comment by silvenon** [comment]
@IanVS I'm looking into this now, for me it works when I ensure the correct order, I don't have to add `babel.config.js` file. Could you tell me more about why you had to?

**Comment by donaldpipowitch** [comment]
I just tried it in a small project (all deps up-to-date), but I can't get it to work.

My `gatsby-config.js`:

```js
module.exports = {
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-typescript',
    'gatsby-plugin-linaria',
    'gatsby-mdx'
  ]
};
```

This throws (without a `babel.config.js`):

```
SyntaxError: ../src/components/Header.tsx: Unexpected token (12:19)

  10 | `;
  11 | 
> 12 | export const Header: FC = () => {
     |                    ^
  13 |   const seconds = useLifetime();
  14 |   return (
  15 |     <>
```

It looks like it can't parse the type `: FC`.

I than added a `babel.config.js` which looks like that:

```js
module.exports = {
  presets: [
    'babel-preset-gatsby',
    '@babel/preset-typescript',
    [
      'linaria/babel',
      {
        evaluate: true,
        displayName: process.env.NODE_ENV !== 'production'
      }
    ]
  ]
};
```

Which throws a different error:

```
  Error: [BABEL] unknown: Configuration contains string/RegExp pattern, but no filename was passed to Babel
  
  - config-chain.js:431 matchPattern
    [my-project]/[@babel]/core/lib/config/config-chain.js:431:11
```

**Comment by silvenon** [comment]
@donaldpipowitch hm, I might have an idea what's going on. Keep gatsby-mdx, but temporarily remove gatsby-plugin-linaria from `gatsby-config.js` and add this patched version to your `gatsby-node.js`:

```js
const TYPESCRIPT_RULE_TEST = '\\.tsx?$'

exports.onCreateWebpackConfig = ({ actions, getConfig, rules, stage }) => {
  const { replaceWebpackConfig } = actions
  const config = getConfig()

  const tests = [rules.js().test.source, TYPESCRIPT_RULE_TEST]

  const sourceRules = config.module.rules.filter(({ test }) => {
    if (!test) return false
    return tests.includes(test.source)
  })

  sourceRules.forEach(rule => {
    // gatsby-plugin-typescript doesn't put it in an array
    if (!Array.isArray(rule.use)) {
      rule.use = [rule.use]
    }

    rule.use.push({
      loader: 'linaria/loader',
      options: {
        sourceMap: stage.includes('develop'),
        displayName: stage.includes('develop'),
        babelOptions: {
          presets:
            rule.test.source === TYPESCRIPT_RULE_TEST
              ? ['babel-preset-gatsby', '@babel/preset-typescript']
              : ['babel-preset-gatsby'],
        },
      },
    })
  })

  replaceWebpackConfig(config)
}
```

Let me know if that worked.

**Comment by silvenon** [comment]
I tested it myself and it seems to solve the problem. I published a new patch version.

**Comment by silvenon** [comment]
And thank you all for helping me fix this issue! I don't use TypeScript yet, so your feedback was incredibly useful. 🏆

**Comment by donaldpipowitch** [comment]
Thank you so much @silvenon for the quick response. I just tested your patch and it seems to work without any problems. I don't need a `babel.config.js` and my `gatsby-config.js` is currently just this:


```
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'posts',
        path: `${__dirname}/src/pages/posts`
      }
    },
    'gatsby-plugin-react-helmet',
    'gatsby-mdx',
    'gatsby-plugin-typescript',
    'gatsby-plugin-linaria'
  ]
};
```

Thank you!

**Comment by newash** [comment]
Hey @silvenon, in the latest release (v1.1.2) this looks to be broken again.

**Comment by silvenon** [comment]
@newash could you open a new issue (referencing this one)? It could be that the TS plugin for Gatsby changed in an incompatible way.
