### ISSUE TITLE
Using global styles

### ISSUE THREAD

**Issue by koss-lebedev** [silvenon/gatsby-plugin-linaria#93]
How can global styles be used in a Gatsby application? 

[Documentation says](https://github.com/callstack/linaria/blob/master/docs/BASICS.md) that we can add global styles using the following syntax, but it doesn't get applied:

```js
export const globals = css`
  :global() {
    html {
      box-sizing: border-box;
    }

    *,
    *:before,
    *:after {
      box-sizing: inherit;
    }

    @font-face {
      font-family: 'MaterialIcons';
      src: url(../assets/fonts/MaterialIcons.ttf) format('truetype');
    }
  }
`;
```

Should this be injected by gatsby-plugin somehow? Thank you

**Comment by silvenon** [comment]
It works for me, please provide steps to reproduce (or better yet, a repo).

Btw, I'm not sure why their example contains `export`, since it doesn't have any context.

**Comment by koss-lebedev** [comment]
@silvenon thank you for a quick reply! In your working example, where do you use this `globals` variable? From the docs, I understood that you just need to export in one of the files accessible by Gatbsy (similar to how fragments work) and it should be enough, but maybe I'm wrong

**Comment by silvenon** [comment]
The best place for it is probably your layout file, the one you use for wrapping every page. That way those styles will be included in all pages. You might not even need to assign it to a variable, because I don't know what you would do with it, try to just run:

```js
css`
  /* ... */
`
```

but I'm not 100% sure about that. The point is that it has to reside in the file which is being imported from somewhere.

**Comment by koss-lebedev** [comment]
Thank you so much for you help, it actually does work! Originally, I was trying to include it in a file inside `pages` folder, which didn't work for some reason, but when I imported it inside one of the components, it worked.

**Comment by silvenon** [comment]
For me adding it to a page works as well, this is my `page/index.js`:

```jsx
import React from 'react'
import { css } from 'linaria'

css`
  :global() {
    html {
      background: black;
      color: #fff;
    }
  }
`

const Home = () => <h1>Hello World!</h1>

export default Home
```

I hope you'll figure it out.
